import Head from 'next/head'
import { Navbar } from '../components/Navbar'
import QrCodeReader from 'react-qrcode-reader'
import contractProduct from '../../backend/artifacts/contracts/Product.sol/Product.json'
import { use, useEffect, useState } from 'react'
import { PRODUCT_CONTRACT_ADDRESS } from '@/constant'
import { Contract, ethers, providers } from 'ethers'
import React from 'react'

export default function Customer() {
  const [productContract, setProductContract] = useState(null)
  const [riceDetail, setRiceDetail] = useState([])
  const [showQr, setShowQr] = useState(true)

  // Get Contract
  useEffect(() => {
    if (!window.ethereum) return
    const provider = new providers.Web3Provider(window.ethereum)
    const signer = provider.getSigner()
    let productContract = new Contract(
      PRODUCT_CONTRACT_ADDRESS,
      contractProduct.abi,
      signer,
    )
    setProductContract(productContract)
  }, [])

  const getRice = (code) => {
    productContract.getRiceDetail(code).then((data) => {
      setRiceDetail(data)
      setShowQr(false)
    })
  }

  const returnBack = () => {
    setShowQr(true)
    setRiceDetail([])
  }

  const previewStyle = {
    height: 240,
    width: 320,
  }

  return (
    <>
      <Head>
        <title>Supply Chain Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen bg-sky-200">
        <Navbar />
        {showQr && (
          <QrCodeReader delay={100} width={600} height={500} action={getRice} />
        )}
        {!showQr && riceDetail && (
          <>
            <div className="flex justify-center mt-4">
              <div className="block rounded-lg shadow-lg bg-white text-center">
                <div className="py-3 px-6 border-b border-gray-300">
                  {riceDetail[1]}
                </div>
                <div className="p-6">
                  <p className="text-gray-700 text-base mb-4">
                    Name: {riceDetail[2]}
                  </p>
                  <p className="text-gray-700 text-base mb-4">
                    Price: {riceDetail[3].toNumber()}
                  </p>
                  <p className="text-gray-700 text-base mb-4">
                    Weight: {riceDetail[4].toNumber()}
                  </p>
                  <p className="text-gray-700 text-base mb-4">
                    Quality Approved: {riceDetail[5] ? 'True' : 'False'}
                  </p>
                  <p className="text-gray-700 text-base mb-4">
                    Owner Id: {riceDetail[7]}
                  </p>
                  <p className="text-gray-700 text-base mb-4">
                    Manufacturer Id: {riceDetail[8]}
                  </p>
                  <p className="text-gray-700 text-base mb-4">
                    Farm Name: {riceDetail[0][4]}
                  </p>
                  <p className="text-gray-700 text-base mb-4">
                    Farm Latitude: {riceDetail[0][5]}
                  </p>
                  <p className="text-gray-700 text-base mb-4">
                    Farm Longitude: {riceDetail[0][6]}
                  </p>
                  <p className="text-gray-700 text-base mb-4">
                    Paddy Variety: {riceDetail[0][7]}
                  </p>
                </div>
              </div>
            </div>
            <button
              onClick={() => returnBack()}
              className="py-2 px-4 bg-blue-500 text-white rounded hover:bg-blue-600 active:bg-blue-700 disabled:opacity-50"
            >
              Return to QR Scanner
            </button>
          </>
        )}
      </div>
    </>
  )
}
